<?php

use Illuminate\Database\Seeder;

class Provincia extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $ubprovincia = array(
                    array('id' => '1','provincia' => 'CHACHAPOYAS ','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '2','provincia' => 'BAGUA','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '3','provincia' => 'BONGARA','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '4','provincia' => 'CONDORCANQUI','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '5','provincia' => 'LUYA','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '6','provincia' => 'RODRIGUEZ DE MENDOZA','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '7','provincia' => 'UTCUBAMBA','departamento_id' => '1','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '8','provincia' => 'HUARAZ','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '9','provincia' => 'AIJA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '10','provincia' => 'ANTONIO RAYMONDI','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '11','provincia' => 'ASUNCION','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '12','provincia' => 'BOLOGNESI','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '13','provincia' => 'CARHUAZ','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '14','provincia' => 'CARLOS FERMIN FITZCARRALD','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '15','provincia' => 'CASMA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '16','provincia' => 'CORONGO','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '17','provincia' => 'HUARI','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '18','provincia' => 'HUARMEY','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '19','provincia' => 'HUAYLAS','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '20','provincia' => 'MARISCAL LUZURIAGA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '21','provincia' => 'OCROS','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '22','provincia' => 'PALLASCA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '23','provincia' => 'POMABAMBA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '24','provincia' => 'RECUAY','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '25','provincia' => 'SANTA','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '26','provincia' => 'SIHUAS','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '27','provincia' => 'YUNGAY','departamento_id' => '2','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '28','provincia' => 'ABANCAY','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '29','provincia' => 'ANDAHUAYLAS','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '30','provincia' => 'ANTABAMBA','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '31','provincia' => 'AYMARAES','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '32','provincia' => 'COTABAMBAS','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '33','provincia' => 'CHINCHEROS','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '34','provincia' => 'GRAU','departamento_id' => '3','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '35','provincia' => 'AREQUIPA','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '36','provincia' => 'CAMANA','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '37','provincia' => 'CARAVELI','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '38','provincia' => 'CASTILLA','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '39','provincia' => 'CAYLLOMA','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '40','provincia' => 'CONDESUYOS','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '41','provincia' => 'ISLAY','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '42','provincia' => 'LA UNION','departamento_id' => '4','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '43','provincia' => 'HUAMANGA','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '44','provincia' => 'CANGALLO','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '45','provincia' => 'HUANCA SANCOS','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '46','provincia' => 'HUANTA','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '47','provincia' => 'LA MAR','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '48','provincia' => 'LUCANAS','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '49','provincia' => 'PARINACOCHAS','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '50','provincia' => 'PAUCAR DEL SARA SARA','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '51','provincia' => 'SUCRE','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '52','provincia' => 'VICTOR FAJARDO','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '53','provincia' => 'VILCAS HUAMAN','departamento_id' => '5','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '54','provincia' => 'CAJAMARCA','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '55','provincia' => 'CAJABAMBA','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '56','provincia' => 'CELENDIN','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '57','provincia' => 'CHOTA ','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '58','provincia' => 'CONTUMAZA','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '59','provincia' => 'CUTERVO','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '60','provincia' => 'HUALGAYOC','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '61','provincia' => 'JAEN','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '62','provincia' => 'SAN IGNACIO','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '63','provincia' => 'SAN MARCOS','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '64','provincia' => 'SAN PABLO','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '65','provincia' => 'SANTA CRUZ','departamento_id' => '6','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '66','provincia' => 'CALLAO','departamento_id' => '7','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '67','provincia' => 'CUSCO','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '68','provincia' => 'ACOMAYO','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '69','provincia' => 'ANTA','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '70','provincia' => 'CALCA','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '71','provincia' => 'CANAS','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '72','provincia' => 'CANCHIS','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '73','provincia' => 'CHUMBIVILCAS','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '74','provincia' => 'ESPINAR','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '75','provincia' => 'LA CONVENCION','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '76','provincia' => 'PARURO','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '77','provincia' => 'PAUCARTAMBO','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '78','provincia' => 'QUISPICANCHI','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '79','provincia' => 'URUBAMBA','departamento_id' => '8','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '80','provincia' => 'HUANCAVELICA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '81','provincia' => 'ACOBAMBA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '82','provincia' => 'ANGARAES','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '83','provincia' => 'CASTROVIRREYNA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '84','provincia' => 'CHURCAMPA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '85','provincia' => 'HUAYTARA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '86','provincia' => 'TAYACAJA','departamento_id' => '9','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '87','provincia' => 'HUANUCO','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '88','provincia' => 'AMBO','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '89','provincia' => 'DOS DE MAYO','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '90','provincia' => 'HUACAYBAMBA','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '91','provincia' => 'HUAMALIES','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '92','provincia' => 'LEONCIO PRADO','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '93','provincia' => 'MARA&Ntilde;ON','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '94','provincia' => 'PACHITEA','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '95','provincia' => 'PUERTO INCA','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '96','provincia' => 'LAURICOCHA','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '97','provincia' => 'YAROWILCA','departamento_id' => '10','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '98','provincia' => 'ICA','departamento_id' => '11','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '99','provincia' => 'CHINCHA','departamento_id' => '11','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '100','provincia' => 'NAZCA','departamento_id' => '11','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '101','provincia' => 'PALPA','departamento_id' => '11','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '102','provincia' => 'PISCO','departamento_id' => '11','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '103','provincia' => 'HUANCAYO','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '104','provincia' => 'CONCEPCION','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '105','provincia' => 'CHANCHAMAYO','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '106','provincia' => 'JAUJA','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '107','provincia' => 'JUNIN','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '108','provincia' => 'SATIPO','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '109','provincia' => 'TARMA','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '110','provincia' => 'YAULI','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '111','provincia' => 'CHUPACA','departamento_id' => '12','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '112','provincia' => 'TRUJILLO','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '113','provincia' => 'ASCOPE','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '114','provincia' => 'BOLIVAR','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '115','provincia' => 'CHEPEN','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '116','provincia' => 'JULCAN','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '117','provincia' => 'OTUZCO','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '118','provincia' => 'PACASMAYO','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '119','provincia' => 'PATAZ','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '120','provincia' => 'SANCHEZ CARRION','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '121','provincia' => 'SANTIAGO DE CHUCO','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '122','provincia' => 'GRAN CHIMU','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '123','provincia' => 'VIRU','departamento_id' => '13','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '124','provincia' => 'CHICLAYO','departamento_id' => '14','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '125','provincia' => 'FERRE&Ntilde;AFE','departamento_id' => '14','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '126','provincia' => 'LAMBAYEQUE','departamento_id' => '14','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '127','provincia' => 'LIMA','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '128','provincia' => 'BARRANCA','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '129','provincia' => 'CAJATAMBO','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '130','provincia' => 'CANTA','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '131','provincia' => 'CA&Ntilde;ETE','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '132','provincia' => 'HUARAL','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '133','provincia' => 'HUAROCHIRI','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '134','provincia' => 'HUAURA','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '135','provincia' => 'OYON','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '136','provincia' => 'YAUYOS','departamento_id' => '15','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '137','provincia' => 'MAYNAS','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '138','provincia' => 'ALTO AMAZONAS','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '139','provincia' => 'LORETO','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '140','provincia' => 'MARISCAL RAMON CASTILLA','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '141','provincia' => 'REQUENA','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '142','provincia' => 'UCAYALI','departamento_id' => '16','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '143','provincia' => 'TAMBOPATA','departamento_id' => '17','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '144','provincia' => 'MANU','departamento_id' => '17','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '145','provincia' => 'TAHUAMANU','departamento_id' => '17','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '146','provincia' => 'MARISCAL NIETO','departamento_id' => '18','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '147','provincia' => 'GENERAL SANCHEZ CERRO','departamento_id' => '18','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '148','provincia' => 'ILO','departamento_id' => '18','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '149','provincia' => 'PASCO','departamento_id' => '19','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '150','provincia' => 'DANIEL ALCIDES CARRION','departamento_id' => '19','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '151','provincia' => 'OXAPAMPA','departamento_id' => '19','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '152','provincia' => 'PIURA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '153','provincia' => 'AYABACA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '154','provincia' => 'HUANCABAMBA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '155','provincia' => 'MORROPON','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '156','provincia' => 'PAITA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '157','provincia' => 'SULLANA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '158','provincia' => 'TALARA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '159','provincia' => 'SECHURA','departamento_id' => '20','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '160','provincia' => 'PUNO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '161','provincia' => 'AZANGARO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '162','provincia' => 'CARABAYA','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '163','provincia' => 'CHUCUITO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '164','provincia' => 'EL COLLAO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '165','provincia' => 'HUANCANE','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '166','provincia' => 'LAMPA','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '167','provincia' => 'MELGAR','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '168','provincia' => 'MOHO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '169','provincia' => 'SAN ANTONIO DE PUTINA','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '170','provincia' => 'SAN ROMAN','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '171','provincia' => 'SANDIA','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '172','provincia' => 'YUNGUYO','departamento_id' => '21','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '173','provincia' => 'MOYOBAMBA','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '174','provincia' => 'BELLAVISTA','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '175','provincia' => 'EL DORADO','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '176','provincia' => 'HUALLAGA','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '177','provincia' => 'LAMAS','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '178','provincia' => 'MARISCAL CACERES','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '179','provincia' => 'PICOTA','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '180','provincia' => 'RIOJA','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '181','provincia' => 'SAN MARTIN','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '182','provincia' => 'TOCACHE','departamento_id' => '22','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '183','provincia' => 'TACNA','departamento_id' => '23','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '184','provincia' => 'CANDARAVE','departamento_id' => '23','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '185','provincia' => 'JORGE BASADRE','departamento_id' => '23','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '186','provincia' => 'TARATA','departamento_id' => '23','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '187','provincia' => 'TUMBES','departamento_id' => '24','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '188','provincia' => 'CONTRALMIRANTE VILLAR','departamento_id' => '24','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '189','provincia' => 'ZARUMILLA','departamento_id' => '24','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '190','provincia' => 'CORONEL PORTILLO','departamento_id' => '25','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '191','provincia' => 'ATALAYA','departamento_id' => '25','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '192','provincia' => 'PADRE ABAD','departamento_id' => '25','created_at' => NULL,'updated_at' => NULL),
                    array('id' => '193','provincia' => 'PURUS','departamento_id' => '25','created_at' => NULL,'updated_at' => NULL)
                    );
        \DB::table('ubprovincia')->insert($ubprovincia);            
    }
}
